# Generated by Django 5.0.1 on 2024-02-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivoire_road', '0003_utilisateur_is_active_utilisateur_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
